name: Generate and Deploy Diagram

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_TOKEN }}
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Rename JS file to MJS
      run: |
        cd img
        mv generate-diagram.js generate-diagram.mjs

    - name: Create package.json
      run: |
        cat > package.json << EOL
        {
          "name": "data-infrastructure-diagram",
          "version": "1.0.0",
          "description": "Data Infrastructure Diagram Generator",
          "type": "module",
          "main": "img/generate-diagram.mjs",
          "scripts": {
            "generate": "node img/generate-diagram.mjs"
          },
          "dependencies": {
            "d3": "^7.8.5",
            "jsdom": "^22.1.0",
            "sharp": "^0.32.6"
          }
        }
        EOL

    - name: Install dependencies
      run: npm install

    - name: Generate diagrams
      run: npm run generate

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Add date to commit message
      run: |
        echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Commit and push if changed
      run: |
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
        git pull origin main --rebase
        git add data_infrastructure.svg platform.png img/generate-diagram.mjs
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update infrastructure diagrams for ${{ env.CURRENT_DATE }} [skip ci]" && git push origin main --force)
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: infrastructure-diagrams-${{ env.CURRENT_DATE }}
        path: |
          data_infrastructure.svg
          platform.png
        compression-level: 9
        retention-days: 90